version: '2'
services:
    jhipsterpress-app:
        image: jhipsterpress
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterpress-postgresql:5432/jhipsterpress
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterpress-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterpress-postgresql
